json.id @user.id
json.username @user.username
json.email @user.email
json.firstname @user.firstname
json.lastname @user.lastname
json.birthday @user.birthday
json.gender @user.gender
json.profile @user.profile
json.albums @user.albums
